CREATE TABLE Box(
	_ID INTEGER PRIMARY KEY NOT NULL,
	name TEXT,
	location TEXT
);
CREATE TABLE Observation(
	_ID INTEGER PRIMARY KEY NOT NULL,
	box_key INTEGER,
	time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY(box_key)REFERENCES Box(_ID)
);